<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 9/15/2017
 * Time: 7:09 PM
 */

namespace amintado\wordpress;


use Yii;
use yii\web\BadRequestHttpException;

class Module extends \yii\base\Module
{
    public $id = 'atwordpress';
    public $WeblogTitle='amintado Yii2 WordPress Module';
    public $WeblogUsername='wpadmin';
    public $WeblogEmail='amintado@gmail.com';
    public $WeblogPassword='123456789';
    public $WeblogPublic=1;
    public $WeblogPrefix='taban_';
    var $controllerNamespace = 'amintado\wordpress\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->id = 'atwordpress';
    }

}