<?php
/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 9/15/2017
 * Time: 7:33 PM
 */


namespace amintado\wordpress\controllers;


use amintado\wordpress\migrations\m170915_170101_wp;
use Exception;
use Yii;
use yii\web\Controller;
use yii\web\View;

class DefaultController extends Controller
{

    public function actionIndex()
    {
        echo 'ok;Finished';


    }

    public function init()
    {


        parent::init(); // TODO: Change the autogenerated stub

        if (empty(realpath(__DIR__ . '/../../../../cms'))) {

            mkdir(__DIR__ . '/../../../../cms', 0777, true);
            $this->copy_directory(realpath(__DIR__ . '/../wordpress/') . '/', realpath(__DIR__ . '/../../../../cms/') . '/');
        }


        // $migrate=new m170915_170101_wp();
        //$migrate->safeUp();


        preg_match('/' . 'dbname' . '=([^;]*)/', Yii::$app->db->dsn, $match);
        define('DB_NAME', $match[1]);
        define('DB_USER', Yii::$app->db->username);
        define('DB_PASSWORD', Yii::$app->db->password);
        $weblog_title = Yii::$app->getModule('cms')->WeblogTitle;
        $user_name = Yii::$app->getModule('cms')->WeblogUsername;
        $admin_email = Yii::$app->getModule('cms')->WeblogEmail;
        $admin_password = Yii::$app->getModule('cms')->WeblogPassword;
        $prefix = Yii::$app->getModule('cms')->WeblogPrefix;
        preg_match('/' . 'host' . '=([^;]*)/', Yii::$app->db->dsn, $match);
        define('DB_HOST', $match[1]);

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "http://".$_SERVER['SERVER_NAME']."/cms/wp-admin/setup-config.php?step=2&language=fa_IR");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "dbname=".DB_NAME."&uname=".DB_USER."&pwd=".DB_PASSWORD."&dbhost=".DB_HOST."&prefix=_wp&Submit=submit");
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = "Content-Type: application/x-www-form-urlencoded";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);


        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "http://".$_SERVER['SERVER_NAME']."/cms/wp-admin/install.php?step=2");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "weblog_title=".$weblog_title."&user_name=".$user_name."&admin_password=".$admin_password."&admin_password2=".$admin_password."&admin_email=".$admin_email."&blog_public=checked&Submit=submit");
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = "Content-Type: application/x-www-form-urlencoded";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);

        $this->redirect('/cms');

    }

    function copy_directory($src, $dst)
    {
        $dir = opendir($src);
        @mkdir($dst);
        while (false !== ($file = readdir($dir))) {
            if (($file != '.') && ($file != '..')) {
                if (is_dir($src . '/' . $file)) {
                    $this->copy_directory($src . '/' . $file, $dst . '/' . $file);
                } else {
                    copy($src . '/' . $file, $dst . '/' . $file);
                }
            }
        }
        closedir($dir);
    }


}